services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: fastapi-backend
    environment:
      HASH_KEY: w8ki50zRknmAf18hsBLkOcASX65WTGvgw8ki50zRknmAf18hsBLkOcASX65WTGvg
      HASH_ALGO: HS256
      API_LOGIN: techtest@gmail.com
      API_KEY: 2OZ58K8MYZV56SFA59NG2PQ2HYW4C6280IT
      ACCOUNT: techtest
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./react
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./react:/app
      - /app/node_modules
    command: npm run dev -- --host
    depends_on:
      - backend

  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: Hiboutik
      PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
